# Generated by Django 5.0 on 2023-12-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slader', '0006_clientreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('rented_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
