# Generated by Django 5.0 on 2023-12-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slader', '0007_carrental'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
