# Generated by Django 5.0 on 2023-12-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slader', '0008_tour_destination_tour_duration_days_tour_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrental',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrental',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
