# Generated by Django 5.0 on 2023-12-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slader', '0009_carrental_rental_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
