# Generated by Django 5.0 on 2023-12-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slader', '0010_delete_tour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarRental',
        ),
    ]
