# Generated by Django 5.0 on 2023-12-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
    ]
