# Generated by Django 5.0 on 2023-12-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_car_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
