# Generated by Django 5.0 on 2023-12-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_remove_car_color_remove_car_year_car_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='economy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
