# Generated by Django 5.0 on 2023-12-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0006_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crossover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(blank=True, max_length=100, null=True)),
                ('field2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
