# Generated by Django 5.0 on 2023-12-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0007_crossover'),
    ]

    operations = [
        migrations.CreateModel(
            name='SUV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
