# Generated by Django 5.0 on 2023-12-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0008_suv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minivan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
